In [2]:
import pandas as pd
import sys
sys.path.insert(0, '..')
from dl2_reports import DL2Report
import json

## Test 1: DataFrame with datetime64 columns

In [3]:
# Create a DataFrame with datetime columns already converted
df_datetime = pd.DataFrame({
    'id': [1, 2, 3, 4, 5],
    'name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve'],
    'created_at': pd.to_datetime(['2024-01-01', '2024-02-15', '2024-03-20', '2024-04-10', '2024-05-25']),
    'updated_at': pd.to_datetime(['2024-06-01 10:30:00', '2024-06-15 14:45:00', '2024-07-01 09:15:00', '2024-07-15 16:20:00', '2024-08-01 11:00:00']),
    'score': [95.5, 87.3, 92.1, 88.7, 91.2],
    'active': [True, False, True, True, False]
})

print("DataFrame dtypes:")
print(df_datetime.dtypes)
print("\nDataFrame:")
df_datetime

DataFrame dtypes:
id                     int64
name                  object
created_at    datetime64[ns]
updated_at    datetime64[ns]
score                float64
active                  bool
dtype: object

DataFrame:

   id     name created_at          updated_at  score  active
0   1    Alice 2024-01-01 2024-06-01 10:30:00   95.5    True
1   2      Bob 2024-02-15 2024-06-15 14:45:00   87.3   False
2   3  Charlie 2024-03-20 2024-07-01 09:15:00   92.1    True
3   4    Diana 2024-04-10 2024-07-15 16:20:00   88.7    True
4   5      Eve 2024-05-25 2024-08-01 11:00:00   91.2   False

### Test with ISO format

In [4]:
# Create report with ISO timestamp format
report_iso = DL2Report("Date Test - ISO Format", compress_visuals=False)
report_iso.add_df("test_data", df_datetime.copy(), timestamp_format="iso")

# Check the dtypes in the dataset
print("Dataset dtypes (ISO format):")
print(report_iso.datasets['test_data']['dtypes'])
print("\nExpected: ['number', 'string', 'date', 'date', 'number', 'boolean']")

# Check the actual data values
print("\nFirst record:")
print(report_iso.datasets['test_data']['data'][0])

int64
object
datetime64[ns]
datetime64[ns]
float64
bool
Dataset dtypes (ISO format):
['number', 'string', 'date', 'date', 'number', 'boolean']

Expected: ['number', 'string', 'date', 'date', 'number', 'boolean']

First record:
{'id': 1, 'name': 'Alice', 'created_at': '2024-01-01T00:00:00.000000Z', 'updated_at': '2024-06-01T10:30:00.000000Z', 'score': 95.5, 'active': True}

c:\Users\kameron\Documents\Projects\Web Projects\superbabycart\datalys2-reporting-python-api\examples\..\dl2_reports\report.py:82: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(sample, utc=True)

### Test with Epoch format

In [5]:
# Create report with epoch timestamp format
report_epoch = DL2Report("Date Test - Epoch Format", compress_visuals=False)
report_epoch.add_df("test_data", df_datetime.copy(), timestamp_format="epoch")

# Check the dtypes in the dataset
print("Dataset dtypes (Epoch format):")
print(report_epoch.datasets['test_data']['dtypes'])
print("\nExpected: ['number', 'string', 'date', 'date', 'number', 'boolean']")

# Check the actual data values (should be integers)
print("\nFirst record:")
print(report_epoch.datasets['test_data']['data'][0])
print("\nNote: created_at and updated_at should be integers (epoch timestamps)")

int64
object
datetime64[ns]
datetime64[ns]
float64
bool
Dataset dtypes (Epoch format):
['number', 'string', 'date', 'date', 'number', 'boolean']

Expected: ['number', 'string', 'date', 'date', 'number', 'boolean']

First record:
{'id': 1, 'name': 'Alice', 'created_at': 1704067200, 'updated_at': 1717237800, 'score': 95.5, 'active': True}

Note: created_at and updated_at should be integers (epoch timestamps)

c:\Users\kameron\Documents\Projects\Web Projects\superbabycart\datalys2-reporting-python-api\examples\..\dl2_reports\report.py:82: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(sample, utc=True)

## Test 2: DataFrame with date strings (object dtype)

In [6]:
# Create a DataFrame with date strings that haven't been converted to datetime yet
df_strings = pd.DataFrame({
    'id': [1, 2, 3],
    'event_date': ['2024-01-15', '2024-02-20', '2024-03-10'],  # Date strings
    'event_time': ['2024-01-15 10:30:00', '2024-02-20 14:45:00', '2024-03-10 09:15:00'],  # Datetime strings
    'description': ['Event A', 'Event B', 'Event C'],  # Regular strings
    'count': [10, 20, 30]
})

print("DataFrame dtypes (before conversion):")
print(df_strings.dtypes)
print("\nNote: event_date and event_time are 'object' dtype\n")
df_strings

DataFrame dtypes (before conversion):
id              int64
event_date     object
event_time     object
description    object
count           int64
dtype: object

Note: event_date and event_time are 'object' dtype

   id  event_date           event_time description  count
0   1  2024-01-15  2024-01-15 10:30:00     Event A     10
1   2  2024-02-20  2024-02-20 14:45:00     Event B     20
2   3  2024-03-10  2024-03-10 09:15:00     Event C     30

In [7]:
# Create report - should auto-detect date strings
report_auto = DL2Report("Date Test - Auto Detection", compress_visuals=False)
report_auto.add_df("test_data", df_strings.copy(), timestamp_format="iso")

print("Dataset dtypes (with auto-detection):")
print(report_auto.datasets['test_data']['dtypes'])
print("\nExpected: ['number', 'date', 'date', 'string', 'number']")
print("\nFirst record:")
print(report_auto.datasets['test_data']['data'][0])

int64
datetime64[ns, UTC]
datetime64[ns, UTC]
object
int64
Dataset dtypes (with auto-detection):
['number', 'date', 'date', 'string', 'number']

Expected: ['number', 'date', 'date', 'string', 'number']

First record:
{'id': 1, 'event_date': '2024-01-15T00:00:00.000000Z', 'event_time': '2024-01-15T10:30:00.000000Z', 'description': 'Event A', 'count': 10}

c:\Users\kameron\Documents\Projects\Web Projects\superbabycart\datalys2-reporting-python-api\examples\..\dl2_reports\report.py:82: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(sample, utc=True)

## Test 3: Verify in compiled HTML

In [9]:
# Create a complete report with visuals
final_report = DL2Report("Date Column Test Report", compress_visuals=False)

# Add both datasets
final_report.add_df("datetime_iso", df_datetime.copy(), timestamp_format="iso")
final_report.add_df("datetime_epoch", df_datetime.copy(), timestamp_format="epoch")
final_report.add_df("string_dates", df_strings.copy(), timestamp_format="iso")

# Add a page with a table
page = final_report.add_page("Test Results")
row = page.add_row()
row.add(
    Table(dataset_id="datetime_iso", title="Datetime with ISO Format", description="Date columns should be identified as 'date' dtype"))

# Save the report
final_report.save("test_date_dtypes.html")
print("Report saved to test_date_dtypes.html")

# Extract and display the dataset info from compiled report
compiled_html = final_report.compile()
import re
from dl2_reports import Table
json_match = re.search(r'<script id="report-data" type="application/json">(.*?)</script>', compiled_html, re.DOTALL)
if json_match:
    report_data = json.loads(json_match.group(1))
    print("\n=== Dataset dtypes in compiled report ===")
    for ds_name, ds_data in report_data['datasets'].items():
        print(f"\n{ds_name}:")
        print(f"  Columns: {ds_data['columns']}")
        print(f"  Dtypes:  {ds_data['dtypes']}")

int64
object
datetime64[ns]
datetime64[ns]
float64
bool
int64
object
datetime64[ns]
datetime64[ns]
float64
bool
int64
datetime64[ns, UTC]
datetime64[ns, UTC]
object
int64
Report saved to test_date_dtypes.html

=== Dataset dtypes in compiled report ===

datetime_iso:
  Columns: ['id', 'name', 'created_at', 'updated_at', 'score', 'active']
  Dtypes:  ['number', 'string', 'date', 'date', 'number', 'boolean']

datetime_epoch:
  Columns: ['id', 'name', 'created_at', 'updated_at', 'score', 'active']
  Dtypes:  ['number', 'string', 'date', 'date', 'number', 'boolean']

string_dates:
  Columns: ['id', 'event_date', 'event_time', 'description', 'count']
  Dtypes:  ['number', 'date', 'date', 'string', 'number']

c:\Users\kameron\Documents\Projects\Web Projects\superbabycart\datalys2-reporting-python-api\examples\..\dl2_reports\report.py:82: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(sample, utc=True)
c:\Users\kameron\Documents\Projects\Web Projects\superbabycart\datalys2-reporting-python-api\examples\..\dl2_reports\report.py:82: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(sample, utc=True)
c:\Users\kameron\Documents\Projects\Web Projects\superbabycart\datalys2-reporting-python-api\examples\..\dl2_reports\report.py:82: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(sample, utc=True)

## Verification Summary

✅ **All date columns should have dtype='date' in the output, regardless of:**
- Whether they started as datetime64 or object (string) dtype
- Whether they're serialized as ISO strings or epoch integers

The frontend can then properly interpret these as dates for filtering, sorting, and display purposes.